# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site # Fluid theme的title在_config.fluid.yml中设置
title: Meloor's Blog
subtitle: DateBase learning...
description: '回想旋律·美乐奥尔的博客;database,java,c++,python;数据库、java、c++、python'
keywords: 'database,java,c++,python'
author: Meloor
# language: zh-cn #zh-cn #en #zh-CN
language: zh-CN
# language: #国际化
# - zh-cn #zh-cn #en
# - en
# language: en #zh-cn #en
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
# url: http://example.com
# root: / 
# url:  http://meloor.gitee.io/ #仓库名为Meloor(与账户名同名)
# url:  http://meloor.gitee.io/blog/ #blog为gitee仓库名
url:  http://meloor.xyz/ #自定义域名 relative_link: true #把链接改为与根目录的相对位址
root: /  # 点击“home"跳转的目录
# permalink: :year/:month/:day/:title/
permalink: :lang/:category/:title/
permalink_defaults:
  lang: zh-cn
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "static_pages/**/*"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft #[post,page,draft]
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1 #把文件名称转换为 (1) 小写或 (2) 大写,0不转换
render_drafts: false #预览草稿
post_asset_folder: true
relative_link: true #把链接改为与根目录的相对位址, 如果域名不变，建议修改为false使用绝对链接
future: true
highlight: #代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: #代码块的设置, 请参考 PrismJS 进行设置
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: melody
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  repo: git@gitee.com:Meloor/meloor.git
  branch: gh-pages
  message: "deploy to gitee pages"
- type: git
  repo: git@github.com:Meloor/Meloor.github.io.git
  branch: gh-pages
  message: "deploy to github pages"
